name: todo-app
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    command: npm start

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DEBUG=true
    env_file:
      - .env
    command: python src/server.py
