name: todo-app
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - DEBUG=true
    env_file:
      - .env
    command: python src/server.py
    restart: unless-stopped